image: themattrix/tox:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test
  - build
  - deploy

test:
  stage: test
  artifacts:
    paths:
      - htmlcov/
  before_script:
    - pip install tox
  script:
    - tox
  coverage: '/TOTAL.*\s+(\d+%)$/'

build:
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - pip install wheel
  script:
    - python setup.py sdist bdist_wheel

deploy:staging:
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install twine
  variables:
    TWINE_USERNAME: $TEST_PYPI_USERNAME
    TWINE_PASSWORD: $TEST_PYPI_PASSWORD
  script:
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - staging

deploy:pypi:
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install twine
  variables:
    TWINE_USERNAME: $LIVE_PYPI_USERNAME
    TWINE_PASSWORD: $LIVE_PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
    - ^v\d+\.\d+\.\d+$

